pool:
  name: DEV

variables:
  version.MajorMinor: '1.0.0' # Manually adjust the version number as needed. Patch is auto-incremented.
  version.Patch: $[counter(variables['version.MajorMinor'], 0)]
  versionNumber: '$(version.MajorMinor).$(VersionBuild)' 

steps:
- task: PowerShell@2
  displayName: Set the name of the build (i.e. the Build.BuildNumber)
  inputs:
    targetType: 'inline'
    script: |
      [string] $buildName = "$(versionNumber)"
      [string] $buildbranch = "$(Build.SourceBranchName)"
      Write-Host "Setting the name of the build to '$buildName'."
      Write-Host "##vso[build.updatebuildnumber]$buildbranch-$buildName"
- task: CmdLine@1
  displayName: Init submodules
  inputs:
    filename: 'C:\Program Files\Git\cmd\git.exe'
    arguments: 'submodule init'
- task: CmdLine@1
  displayName: Update submodules
  inputs:
    filename: 'C:\Program Files\Git\cmd\git.exe'
    arguments: 'submodule update'
- task: BatchScript@1
  displayName: 'Delphivariablen für Build vorbereiten'
  inputs:
    filename: PrepareBuild.cmd
    modifyEnvironment: true

- task: MSBuild@1
  displayName: 'Erzeuge Version 32-Bit'
  inputs:
    solution: PCMUpdate.dproj
    platform: Win32
    msbuildArguments: '/t:Clean;Build;CompressWin32 /p:config=Release /p:platform=Win32'

- task: BatchScript@1
  displayName: erzeugte Versionen ins Setupverzeichnis kopieren 
  inputs:
    filename: PrepareCopy.cmd
    modifyEnvironment: true

- task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
  displayName: 'CleanUp Agent Directories'

- task: gitsync@1
  displayName: 'Synchronsiere mit GitHub'
  inputs:
    GitRepoUrl: 'https://github.com/JtheK1984/PCMUpdate.git'
  
- task: BatchScript@1
  displayName: Cleanup Buildverzeichnis
  inputs:
    filename: E:\PrepareCleanup.cmd